; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include <idp.iss>

#define MyAppName "Ecopath with Ecosim"
#define MyAppVersion "6.6_dev"
#define MyAppExeName "ewe6.exe"
#define MyAppPublisher "UBC Institute for Oceans and Fisheries & Ecopath International Initiative"

[Setup]
SignTool=Signtool
WizardImageFile=C:\Setup\EwE5Logo.bmp
WizardSmallImageFile=C:\Setup\EwE6Header.bmp
WizardImageStretch=False
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppCopyright={#MyAppPublisher}
AppId={{41587FF4-2D37-4CF2-8D45-0AA1378637A4}
SetupIconFile=C:\Setup\Ecopath_install.ico
UninstallDisplayIcon={app}\{#MyAppName}
AllowNoIcons=True
AppPublisher={#MyAppPublisher}
AppPublisherURL=http://ecopathinternational.org
AppSupportURL=mailto:support@ecopath.org
MinVersion=0,5.01sp3
DefaultDirName={pf}\{#MyAppName} {#MyAppVersion}
DefaultGroupName={#MyAppName} {#MyAppVersion}
AlwaysShowGroupOnReadyPage=True
AlwaysShowDirOnReadyPage=True
SolidCompression=True
Compression=zip 
UninstallDisplayName={#MyAppName} {#MyAppVersion}
UninstallDisplayIcon={app}\{#MyAppName}
OutputBaseFilename=ewe
OutputDir=C:\Temp\Setup

[Dirs]
Name: "{app}\Includes\LPSolve\"
Name: "{app}\Includes\LPSolve\win32\"
Name: "{app}\Includes\LPSolve\win64\"
Name: "{app}\Resources\"
Name: "{app}\Tools\"
Name: "{app}\UserGuide\"
Name: "{app}\Plugins\"

[Files]
Source: "C:\Temp\Build\EwEMultiSimPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\automation\multisim
Source: "C:\Temp\Build\EwENetworkAnalysis.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\analysis\na
Source: "C:\Temp\Build\EwEPlugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\EwEPrebalPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\analysis\prebal
Source: "C:\Temp\Build\EwERemarksPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\ui\remarks
Source: "C:\Temp\Build\EwEResultsExtractorPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\output\resultextractor
Source: "C:\Temp\Build\EwEShapeGridPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\ui\shapegrid
Source: "C:\Temp\Build\EwEStepwiseFittingPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\automation\stepwisef
Source: "C:\Temp\Build\EwEUtils.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\EwEValueChainPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\analysis\valuechain
Source: "C:\Temp\Build\EwEWoRMSPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\input\worms
Source: "C:\Temp\Build\Interop.JRO.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\Ionic.Zip.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\Microsoft.GLEE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\Microsoft.Office.Interop.Access.Dao.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\BuildBot\slave\Ecopath6\Database\Generic_37.EwEmdb"; DestDir: "{userdocs}\EwE sample databases"; Flags: ignoreversion; Components: databases
Source: "C:\BuildBot\slave\Ecopath6\Database\Anchovy Bay Spatial.ewemdb"; DestDir: "{userdocs}\EwE sample databases"; Flags: ignoreversion; Components: databases
Source: "C:\BuildBot\slave\Ecopath6\Database\Tampa_Bay.EwEmdb"; DestDir: "{userdocs}\EwE sample databases"; Flags: ignoreversion; Components: databases
Source: "C:\BuildBot\slave\Ecopath6\Database\Georgia_Strait.EwEmdb"; DestDir: "{userdocs}\EwE sample databases"; Flags: ignoreversion; Components: databases
; Source: "C:\Temp\Build\ProjNet.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\ScientificInterfaceShared.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\SourceGrid2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\SourceLibrary.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\WeifenLuo.WinFormsUI.Docking.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\ZedGraph.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\EwE6.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\EwEAquamapsEnvDataImporterPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\input\aquamaps
Source: "C:\Temp\Build\EwECore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Temp\Build\EwEEcologicalIndicatorsPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\analysis\ecolind
Source: "C:\Temp\Build\EwEEcoTroph.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\analysis\ecotroph
Source: "C:\Temp\Build\EwEModelFromEcosimPlugin.dll"; DestDir: "{app}\Plugins"; Flags: ignoreversion; Components: plugin\output\modelfromsim
Source: "C:\Temp\Build\Includes\LPSolve\win32\lpsolve55.dll"; DestDir: "{app}\Includes\LPSolve\win32\"; Flags: ignoreversion
Source: "C:\Temp\Build\Includes\LPSolve\win64\lpsolve55.dll"; DestDir: "{app}\Includes\LPSolve\win64\"; Flags: ignoreversion
Source: "C:\Temp\Build\Resources\gpl-2.0.txt"; DestDir: "{app}\Resources\"; Flags: ignoreversion
Source: "C:\Temp\Build\Tools\code_for_plotting_dirichlets.R"; DestDir: "{app}\Tools\"; Flags: ignoreversion
Source: "C:\Temp\Build\UserGuide\ChristensenValueChainMS.pdf"; DestDir: "{app}\UserGuide\"; Flags: ignoreversion; Components: plugin\analysis\valuechain
Source: "C:\Temp\Build\UserGuide\EwE model from time step.pdf"; DestDir: "{app}\UserGuide\"; Flags: ignoreversion
Source: "C:\Temp\Build\UserGuide\EwE6_userguide.chm"; DestDir: "{app}\UserGuide\"; Flags: ignoreversion; Components: userguide
Source: "C:\Temp\Build\UserGuide\EwEMultiSimPlugin.pdf"; DestDir: "{app}\UserGuide\"; Flags: ignoreversion
Source: "C:\Temp\Build\UserGuide\Link - 2010 - Adding rigor to ecological network models by evalu.pdf"; DestDir: "{app}\UserGuide\"; Flags: ignoreversion; Components: plugin\analysis\prebal
Source: "C:\Temp\Build\UserGuide\ResultsExtractorPlug.pdf"; DestDir: "{app}\UserGuide\"; Flags: ignoreversion; Components: plugin\output\resultextractor

[Components]
Name: "userguide"; Description: "EwE user guide (2008)"; Types: full custom
Name: "databases"; Description: "Sample EwE models"; Types: full custom
Name: "plugin"; Description: "Plug-ins"; Types: full custom
Name: "plugin\analysis"; Description: "Analysis"; Types: full custom
Name: "plugin\analysis\ecolind"; Description: "Ecological Indicators"; Types: full
Name: "plugin\analysis\ecotroph"; Description: "EcoTroph"; Types: custom full
Name: "plugin\analysis\na"; Description: "Network Analysis"; Types: compact custom full
Name: "plugin\analysis\prebal"; Description: "Pre-balance diagnostics"; Types: full custom
Name: "plugin\analysis\valuechain"; Description: "Value chain"; Types: full
Name: "plugin\input"; Description: "Data retrieval"; Types: full custom
Name: "plugin\input\worms"; Description: "WoRMS taxonomy search"; Types: full
Name: "plugin\input\aquamaps"; Description: "Aquamaps functional response importer"; Types: full
Name: "plugin\output"; Description: "Data export"; Types: full
Name: "plugin\output\modelfromsim"; Description: "Ecopath model from Ecosim"; Types: full
Name: "plugin\output\resultextractor"; Description: "Results extractor"; Types: full
Name: "plugin\automation"; Description: "Automation"; Types: full custom
Name: "plugin\automation\multisim"; Description: "Multi-Sim"; Types: custom full
Name: "plugin\automation\stepwisef"; Description: "Stepwise Fitting"; Types: full
Name: "plugin\ui"; Description: "Usability"; Types: full custom
Name: "plugin\ui\remarks"; Description: "Remarks collector"; Types: full custom
Name: "plugin\ui\shapegrid"; Description: "Shape grids"; Types: full custom

[Tasks]
Name: "desktopicon"; Description: "Add desktop icon"
Name: "quicklaunchicon"; Description: "Add quick launch icon"

[Icons]
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon
Name: "{group}\{#MyAppName} {#MyAppVersion}"; Filename: "{app}\{#MyAppExeName}"; IconFilename:  "{app}\{#MyAppExeName}"; Components: userguide
Name: "{group}\User guide"; Filename: "{app}\UserGuide\EwE6_userguide.chm"; IconFilename: "{app}\UserGuide\EwE6_userguide.chm"; Components: userguide
Name: "{group}\Links\Ecopath website"; Filename: "http://www.ecopath.org"
Name: "{group}\Links\Ecopath on Facebook"; Filename: "http://www.facebook.com/eweconsortium"
Name: "{group}\Links\User support"; Filename: "http://www.ecopath.org/support"

[ThirdParty]
UseRelativePaths=True

[Code]
function Framework45IsNotInstalled(): Boolean;
var
  bSuccess: Boolean;
  regVersion: Cardinal;
begin
  Result := True;

  bSuccess := RegQueryDWordValue(HKLM, 'Software\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', regVersion);
  if (True = bSuccess) and (regVersion >= 378389) then begin
    Result := False;
  end;
end; 

procedure InitializeWizard();
begin
 if Framework45IsNotInstalled() then
 begin
   idpAddFile('go.microsoft.com/fwlink', ExpandConstant('{tmp}NetFrameworkInstaller.exe'));
   idpDownloadAfter(wpReady);
 end;
end;

procedure InstallFramework;
var
  StatusText: string;
  ResultCode: Integer;
begin
  StatusText := WizardForm.StatusLabel.Caption;
  WizardForm.StatusLabel.Caption := 'Installing .NET Framework 4.5.2. This might take a few minutes';
  WizardForm.ProgressGauge.Style := npbstMarquee;
  try
    if not Exec(ExpandConstant('{tmp}\NetFrameworkInstaller.exe'), '/passive /norestart', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
    begin
      MsgBox('.NET installation failed with code: ' + IntToStr(ResultCode) + '.', mbError, MB_OK);
    end;
  finally
    WizardForm.StatusLabel.Caption := StatusText;
    WizardForm.ProgressGauge.Style := npbstNormal;

    DeleteFile(ExpandConstant('{tmp}\NetFrameworkInstaller.exe'));
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  case CurStep of
    ssPostInstall:
      begin
        if Framework45IsNotInstalled() then
        begin
          InstallFramework();
        end;
      end;
  end;
end;

[Registry]
; ewefile
Root: HKCR; Subkey: "ewefile\"; ValueType: string; ValueName: ""; ValueData: "Ecopath with Ecosim model"; Flags: uninsdeletekey
Root: HKCR; Subkey: "ewefile\Shell\Open\Command\"; ValueType: string; ValueName: ""; ValueData: """{app}\EwE6.exe"" ""%1""" ;Flags: uninsdeletekey
Root: HKCR; Subkey: "ewefile\DefaultIcon\"; ValueType: string; ValueName: ""; ValueData: "{app}\EwE6.exe,0"; Flags: uninsdeletekey
; ewefile types
Root: HKCR; Subkey: ".ewemdb\"; ValueType: string; ValueName: ""; ValueData: "ewefile"; Flags: uninsdeletekey
Root: HKCR; Subkey: ".eweaccdb\"; ValueType: string; ValueName: ""; ValueData: "ewefile"; Flags: uninsdeletekey
Root: HKCR; Subkey: ".eiixml\"; ValueType: string; ValueName: ""; ValueData: "ewefile"; Flags: uninsdeletekey
; EcoBase URL protocol handler
Root: HKCR; Subkey: "ewe-ecobase\"; ValueType: string; ValueName: ""; ValueData: "URL:ewe-ecobase"; Flags: uninsdeletekey
Root: HKCR; Subkey: "ewe-ecobase\FriendlyTypeName"; ValueType: string; ValueName: ""; ValueData: "Ecopath with Ecosim Ecobase importer"; Flags: uninsdeletekey
Root: HKCR; Subkey: "ewe-ecobase\URL Protocol"; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: "ewe-ecobase\DefaultIcon\"; ValueType: string; ValueName: ""; ValueData: "{app}\EwE6.exe,0"; Flags: uninsdeletekey
Root: HKCR; Subkey: "ewe-ecobase\Shell\Open\Command\"; ValueType: string; ValueName: ""; ValueData: """{app}\EwE6.exe"" ""%1"""; Flags: uninsdeletekey

