' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991-2013 UBC Fisheries Centre, Vancouver BC, Canada.
' ===============================================================================
'

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EcoTroph.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot read file from disk. Original error: {0}.
        '''</summary>
        Friend ReadOnly Property ERROR_LOAD() As String
            Get
                Return ResourceManager.GetString("ERROR_LOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no model loaded, we can&apos;t find EcoTroph input data.
        '''</summary>
        Friend ReadOnly Property ERROR_NO_MODEL_LOADED() As String
            Get
                Return ResourceManager.GetString("ERROR_NO_MODEL_LOADED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The procedure did not yield any results.
        '''</summary>
        Friend ReadOnly Property ERROR_NO_RESULTS() As String
            Get
                Return ResourceManager.GetString("ERROR_NO_RESULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xml files (*.xml)|*.xml.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_XML() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xml files (*.xml)|*.xml|All files (*.*)|*.*.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_XML_ALL() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_XML_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agrocampus Ouest - Fisheries and Aquatic Sciences Center.
        '''</summary>
        Friend ReadOnly Property PLUGIN_AUTHOR() As String
            Get
                Return ResourceManager.GetString("PLUGIN_AUTHOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EcoTroph.
        '''</summary>
        Friend ReadOnly Property PLUGIN_CONTROLTEXT() As String
            Get
                Return ResourceManager.GetString("PLUGIN_CONTROLTEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EcoTroph (ET) is a modelling approach articulated around the idea that an ecosystem can be represented by its biomass distribution across trophic levels. Such an approach, wherein species as such disappear, may be regarded as the ultimate stage in the use of the trophic level metric for ecosystem modelling. By concentrating on biomass flow as a quasi-physical process, it allows aspects of ecosystem functioning to be explored which are complementary to EwE. It provides users with simple tools to quantify the [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PLUGIN_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("PLUGIN_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save an EcoTroph input data file.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVE_ET() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVE_ET", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
