'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CoreDefaults
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwECore.CoreDefaults", GetType(CoreDefaults).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property CORE_ALL_HABITAT() As String
            Get
                Return ResourceManager.GetString("CORE_ALL_HABITAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Combined fleets.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_COMBINEDFLEETS() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_COMBINEDFLEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fish Mortality Shape {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_FISHMORTSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_FISHMORTSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing Rate Shape {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_FISHRATESHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_FISHRATESHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet1.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_FLEET() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group1.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_GROUP() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediation Shape {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_MEDIATIONSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_MEDIATIONSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Scenario.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_SCENARIO() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_SCENARIO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Forcing Shape.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_FORCINGSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_FORCINGSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Group.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_GROUP() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Mediation Shape.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_MEDIATIONSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_MEDIATIONSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_OBJECT_CREATIONTIME() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_OBJECT_CREATIONTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property TIMESERIES_SOURCE_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("TIMESERIES_SOURCE_CLIPBOARD", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
