' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991- 
'    UBC Institute for the Oceans and Fisheries, Vancouver BC, Canada, and 
'    Ecopath International Initiative, Barcelona, Spain
' ===============================================================================
'

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CoreDefaults
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwECore.CoreDefaults", GetType(CoreDefaults).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All fleets.
        '''</summary>
        Friend Shared ReadOnly Property CORE_ALL_FLEETS() As String
            Get
                Return ResourceManager.GetString("CORE_ALL_FLEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (default).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advection.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_ADVECTION() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_ADVECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_BIOMASSFORCING() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_BIOMASSFORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_BIOMASSRELFORCING() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_BIOMASSRELFORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Combined fleets.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_COMBINEDFLEETS() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_COMBINEDFLEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Depth.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_DEPTH() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_DEPTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Environmental driver {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_DRIVER() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_DRIVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excluded cells.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_EXCLUSION() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_EXCLUSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fish Mortality Shape {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_FISHMORTSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_FISHMORTSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing Rate Shape {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_FISHRATESHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_FISHRATESHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet1.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_FLEET() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group1.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_GROUP() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cap. computed ({0}: {1}).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_HABCAP() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_HABCAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cap. ({0}: {1}).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_HABCAP_INPUT() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_HABCAP_INPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Habitat {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_HABITAT() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_HABITAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_HABITAT_ALL() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_HABITAT_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importance {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_IMPORTANCE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_IMPORTANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediation Shape {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_MEDIATIONSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_MEDIATIONSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Migration ({0}: {1}).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_MIGRATION() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_MIGRATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mixed layer depth.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_MIXEDLAYERDEPTH() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_MIXEDLAYERDEPTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marine Protected Areas.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_MPA() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_MPA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seed cells.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_MPASEED() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_MPASEED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port ({0}: {1}).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_PORT() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_PORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port (all fleets).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_PORT_ALL() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_PORT_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regions.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_REGION() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_REGION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contaminants (rel).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_RELCIN() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_RELCIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PP (relative).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_RELPP() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_RELPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sailing cost (all fleets).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_SAIL_ALL() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_SAIL_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sailing cost ({0}: {1}).
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_SAILCOST() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_SAILCOST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Scenario.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_SCENARIO() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_SCENARIO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upwelling.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_UPWELLING() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_UPWELLING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wind.
        '''</summary>
        Friend Shared ReadOnly Property CORE_DEFAULT_WIND() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_WIND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Forcing Shape.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_FORCINGSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_FORCINGSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Group.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_GROUP() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Mediation Shape.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_MEDIATIONSHAPE() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_MEDIATIONSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created {0}.
        '''</summary>
        Friend Shared ReadOnly Property CORE_NEW_OBJECT_CREATIONTIME() As String
            Get
                Return ResourceManager.GetString("CORE_NEW_OBJECT_CREATIONTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Georeferenced ASCII maps.
        '''</summary>
        Friend Shared ReadOnly Property ECOSPACE_WRITER_ASCMAP() As String
            Get
                Return ResourceManager.GetString("ECOSPACE_WRITER_ASCMAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV maps.
        '''</summary>
        Friend Shared ReadOnly Property ECOSPACE_WRITER_CSVMAP() As String
            Get
                Return ResourceManager.GetString("ECOSPACE_WRITER_CSVMAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Region averages.
        '''</summary>
        Friend Shared ReadOnly Property ECOSPACE_WRITER_REGAVG() As String
            Get
                Return ResourceManager.GetString("ECOSPACE_WRITER_REGAVG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left bottom.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_LEFT_BOTTOM() As String
            Get
                Return ResourceManager.GetString("PARAM_LEFT_BOTTOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left top.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_LEFT_TOP() As String
            Get
                Return ResourceManager.GetString("PARAM_LEFT_TOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left point.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_LEFTPOINT() As String
            Get
                Return ResourceManager.GetString("PARAM_LEFTPOINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max..
        '''</summary>
        Friend Shared ReadOnly Property PARAM_MAX() As String
            Get
                Return ResourceManager.GetString("PARAM_MAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mean.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_MEAN() As String
            Get
                Return ResourceManager.GetString("PARAM_MEAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right bottom.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_RIGHT_BOTTOM() As String
            Get
                Return ResourceManager.GetString("PARAM_RIGHT_BOTTOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right top.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_RIGHT_TOP() As String
            Get
                Return ResourceManager.GetString("PARAM_RIGHT_TOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right point.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_RIGHTPOINT() As String
            Get
                Return ResourceManager.GetString("PARAM_RIGHTPOINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SD left.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_SD_LEFT() As String
            Get
                Return ResourceManager.GetString("PARAM_SD_LEFT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SD right.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_SD_RIGHT() As String
            Get
                Return ResourceManager.GetString("PARAM_SD_RIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SD width.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_SD_WIDTH() As String
            Get
                Return ResourceManager.GetString("PARAM_SD_WIDTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steep.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_STEEPNESS() As String
            Get
                Return ResourceManager.GetString("PARAM_STEEPNESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Width.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_WIDTH() As String
            Get
                Return ResourceManager.GetString("PARAM_WIDTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y base.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_YBASE() As String
            Get
                Return ResourceManager.GetString("PARAM_YBASE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y end.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_YEND() As String
            Get
                Return ResourceManager.GetString("PARAM_YEND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y zero.
        '''</summary>
        Friend Shared ReadOnly Property PARAM_YZERO() As String
            Get
                Return ResourceManager.GetString("PARAM_YZERO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From clipboard.
        '''</summary>
        Friend Shared ReadOnly Property SOURCE_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("SOURCE_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to km².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_AREA_KM2() As String
            Get
                Return ResourceManager.GetString("UNIT_AREA_KM2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mi².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_AREA_MI2() As String
            Get
                Return ResourceManager.GetString("UNIT_AREA_MI2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to kcal/m².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_CALORIE() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CALORIE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_CARBON() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CARBON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_DRYWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_DRYWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to J/m².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_JOULES() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_JOULES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg N/m².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_NITROGEN() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_NITROGEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg P/m².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_PHOSPOROUS() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_PHOSPOROUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t/km².
        '''</summary>
        Friend Shared ReadOnly Property UNIT_CURRENCY_WETWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_WETWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dd.
        '''</summary>
        Friend Shared ReadOnly Property UNIT_DECIMALDEGREE() As String
            Get
                Return ResourceManager.GetString("UNIT_DECIMALDEGREE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to km.
        '''</summary>
        Friend Shared ReadOnly Property UNIT_KILOMETER() As String
            Get
                Return ResourceManager.GetString("UNIT_KILOMETER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m.
        '''</summary>
        Friend Shared ReadOnly Property UNIT_METER() As String
            Get
                Return ResourceManager.GetString("UNIT_METER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day.
        '''</summary>
        Friend Shared ReadOnly Property UNIT_TIME_DAY() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_DAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to year.
        '''</summary>
        Friend Shared ReadOnly Property UNIT_TIME_YEAR() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} (compiled {1}).
        '''</summary>
        Friend Shared ReadOnly Property VERSION_EXT_COMPILED() As String
            Get
                Return ResourceManager.GetString("VERSION_EXT_COMPILED", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
