'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

