'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScientificInterfaceShared.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property CheckBoxHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckBoxHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Egg production shape {0}.
        '''</summary>
        Friend ReadOnly Property ECOSIM_DEFAULT_NEWEGGPRODSHAPE() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWEGGPRODSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forcing shape {0}.
        '''</summary>
        Friend ReadOnly Property ECOSIM_DEFAULT_NEWFORCINGSHAPE() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWFORCINGSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New time series {0}.
        '''</summary>
        Friend ReadOnly Property ECOSIM_DEFAULT_NEWTIMESERIES() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWTIMESERIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitmap image (*.bmp)|*.bmp|JPEG image (*.jpg;*.jpeg)|*.jpg;*.jpeg|GIF image (*.gif)|*.gif|PNG image (*.png)|*.png|TIFF image (*.tif;*.tiff)|*.tif;*.tiff.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_IMAGE() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_IMAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AED|UAE Dirham|AFN|Afghanistan Afghani|ALL|Albanian Lek|AMD|Armenian Dram|ANG|Antillean Guilder|AOR|Angolan New Kwanza|ARS|Argentinian Peso|AUD|Australian Dollar|AWG|Aruban Florin|AZM|Azerbaijan Manat|BAM|Bosnian Konvertibilna Marka|BBD|Barbadian Dollar|BDT|Bangladesh Taka|BGN|Bulgarian New Lev|BHD|Bahraini Dinar|BIF|Burundian Franc|BMD|Bermudan Dollar|BND|Brunei Dollar|BOB|Bolivian Boliviano|BRL|Brazilian Real|BSD|Bahamas Dollar|BTN|Bhutan Ngultrum|BWP|Botswana Pula|BYB|Belarussian Ruble|BZD|Belizean Dolla [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GENERIC_CURRENCIES() As String
            Get
                Return ResourceManager.GetString("GENERIC_CURRENCIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; failed to save to file &apos;{1}&apos;: {2}..
        '''</summary>
        Friend ReadOnly Property GENERIC_FILESAVE_FAILURE() As String
            Get
                Return ResourceManager.GetString("GENERIC_FILESAVE_FAILURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; is succesfully saved to file &apos;{1}&apos;..
        '''</summary>
        Friend ReadOnly Property GENERIC_FILESAVE_SUCCES() As String
            Get
                Return ResourceManager.GetString("GENERIC_FILESAVE_SUCCES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {1}.
        '''</summary>
        Friend ReadOnly Property GENERIC_LABEL_CURRENCY() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_CURRENCY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: ({1}, {2}).
        '''</summary>
        Friend ReadOnly Property GENERIC_LABEL_GRAPHVALUE() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_GRAPHVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1}.
        '''</summary>
        Friend ReadOnly Property GENERIC_LABEL_INDEXEDLABEL() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_INDEXEDLABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cursor.
        '''</summary>
        Friend ReadOnly Property GENERIC_TEXT_CURSOR() As String
            Get
                Return ResourceManager.GetString("GENERIC_TEXT_CURSOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no data).
        '''</summary>
        Friend ReadOnly Property GENERIC_TEXT_NODATA() As String
            Get
                Return ResourceManager.GetString("GENERIC_TEXT_NODATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (All).
        '''</summary>
        Friend ReadOnly Property GENERIC_VALUE_ALL() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (N/A).
        '''</summary>
        Friend ReadOnly Property GENERIC_VALUE_NOTAVAILABLE() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_NOTAVAILABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property HEADER_ADD() As String
            Get
                Return ResourceManager.GetString("HEADER_ADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index.
        '''</summary>
        Friend ReadOnly Property HEADER_INDEX() As String
            Get
                Return ResourceManager.GetString("HEADER_INDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month.
        '''</summary>
        Friend ReadOnly Property HEADER_MONTH() As String
            Get
                Return ResourceManager.GetString("HEADER_MONTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property HEADER_VALUE() As String
            Get
                Return ResourceManager.GetString("HEADER_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Values.
        '''</summary>
        Friend ReadOnly Property HEADER_VALUES() As String
            Get
                Return ResourceManager.GetString("HEADER_VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend ReadOnly Property HEADER_YEAR() As String
            Get
                Return ResourceManager.GetString("HEADER_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Fleet:.
        '''</summary>
        Friend ReadOnly Property LABEL_FLEET() As String
            Get
                Return ResourceManager.GetString("LABEL_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Group:.
        '''</summary>
        Friend ReadOnly Property LABEL_GROUP() As String
            Get
                Return ResourceManager.GetString("LABEL_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediating group (weighted) biomass.
        '''</summary>
        Friend ReadOnly Property MEDIATION_X_AXIS_LABEL() As String
            Get
                Return ResourceManager.GetString("MEDIATION_X_AXIS_LABEL", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OptionsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete forcing function &apos;{0}&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property PROMPT_FORCING_DELETE() As String
            Get
                Return ResourceManager.GetString("PROMPT_FORCING_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete {0} forcing functions&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property PROMPT_FORCING_DELETE_MULTIPLE() As String
            Get
                Return ResourceManager.GetString("PROMPT_FORCING_DELETE_MULTIPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete time series &apos;{0}&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property PROMPT_TIMESERIES_DELETE() As String
            Get
                Return ResourceManager.GetString("PROMPT_TIMESERIES_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete {0} time series&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property PROMPT_TIMESERIES_DELETE_MULTIPLE() As String
            Get
                Return ResourceManager.GetString("PROMPT_TIMESERIES_DELETE_MULTIPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change F.
        '''</summary>
        Friend ReadOnly Property RUN_ECOSIM_F_VALUE_CAPTION() As String
            Get
                Return ResourceManager.GetString("RUN_ECOSIM_F_VALUE_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter F~value (or enter a string of comma separated F&apos;s for all fleets).
        '''</summary>
        Friend ReadOnly Property RUN_ECOSIM_F_VALUE_MSG() As String
            Get
                Return ResourceManager.GetString("RUN_ECOSIM_F_VALUE_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change shape type.
        '''</summary>
        Friend ReadOnly Property SHAPE_TYPE_TO_SEASONAL_CAPTION() As String
            Get
                Return ResourceManager.GetString("SHAPE_TYPE_TO_SEASONAL_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing a shape from &apos;Long term&apos; to &apos;Seasonal&apos; will cause your long-term data to be overwritten by a seasonal pattern. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property SHAPE_TYPE_TO_SEASONAL_MSG() As String
            Get
                Return ResourceManager.GetString("SHAPE_TYPE_TO_SEASONAL_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adding time series {0} ....
        '''</summary>
        Friend ReadOnly Property STATUS_TIMESERIES_ADDING() As String
            Get
                Return ResourceManager.GetString("STATUS_TIMESERIES_ADDING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating time series {0}....
        '''</summary>
        Friend ReadOnly Property STATUS_TIMESERIES_UPDATING() As String
            Get
                Return ResourceManager.GetString("STATUS_TIMESERIES_UPDATING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to kcal/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_CALORIE() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CALORIE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_CARBON() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CARBON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_DRYWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_DRYWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to J/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_JOULES() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_JOULES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg N/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_NITROGEN() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_NITROGEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg P/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_PHOSPOROUS() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_PHOSPOROUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t/km².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_WETWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_WETWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day.
        '''</summary>
        Friend ReadOnly Property UNIT_TIME_DAY() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_DAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to year.
        '''</summary>
        Friend ReadOnly Property UNIT_TIME_YEAR() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_YEAR", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property WarningHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarningHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
