'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScientificInterfaceShared.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AED|UAE Dirham|AFN|Afghanistan Afghani|ALL|Albanian Lek|AMD|Armenian Dram|ANG|Antillean Guilder|AOR|Angolan New Kwanza|ARS|Argentinian Peso|AUD|Australian Dollar|AWG|Aruban Florin|AZM|Azerbaijan Manat|BAM|Bosnian Konvertibilna Marka|BBD|Barbadian Dollar|BDT|Bangladesh Taka|BGN|Bulgarian New Lev|BHD|Bahraini Dinar|BIF|Burundian Franc|BMD|Bermudan Dollar|BND|Brunei Dollar|BOB|Bolivian Boliviano|BRL|Brazilian Real|BSD|Bahamas Dollar|BTN|Bhutan Ngultrum|BWP|Botswana Pula|BYB|Belarussian Ruble|BZD|Belizean Dolla [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GENERIC_CURRENCIES() As String
            Get
                Return ResourceManager.GetString("GENERIC_CURRENCIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {1}.
        '''</summary>
        Friend ReadOnly Property GENERIC_LABEL_CURRENCY() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_CURRENCY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1}.
        '''</summary>
        Friend ReadOnly Property GENERIC_LABEL_INDEXEDLABEL() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_INDEXEDLABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cursor.
        '''</summary>
        Friend ReadOnly Property GENERIC_TEXT_CURSOR() As String
            Get
                Return ResourceManager.GetString("GENERIC_TEXT_CURSOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no data).
        '''</summary>
        Friend ReadOnly Property GENERIC_TEXT_NODATA() As String
            Get
                Return ResourceManager.GetString("GENERIC_TEXT_NODATA", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to kcal/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_CALORIE() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CALORIE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_CARBON() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CARBON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_DRYWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_DRYWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to J/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_JOULES() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_JOULES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg N/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_NITROGEN() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_NITROGEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg P/m².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_PHOSPOROUS() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_PHOSPOROUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t/km².
        '''</summary>
        Friend ReadOnly Property UNIT_CURRENCY_WETWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_WETWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day.
        '''</summary>
        Friend ReadOnly Property UNIT_TIME_DAY() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_DAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to year.
        '''</summary>
        Friend ReadOnly Property UNIT_TIME_YEAR() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (N/A).
        '''</summary>
        Friend ReadOnly Property VALUE_NOTAVAILABLE() As String
            Get
                Return ResourceManager.GetString("VALUE_NOTAVAILABLE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
