'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScientificInterfaceShared.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property BreakpointHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BreakpointHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CalculatorHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalculatorHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property certificate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("certificate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CheckBoxHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckBoxHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Collapsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapsed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CommentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property compareversionsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compareversionsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property DeleteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ecopath_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ecopath_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ecosim_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ecosim_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediating group.
        '''</summary>
        Public ReadOnly Property ECOSIM_DEF_MED_X_AXIS() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEF_MED_X_AXIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Egg production shape {0}.
        '''</summary>
        Public ReadOnly Property ECOSIM_DEFAULT_NEWEGGPRODSHAPE() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWEGGPRODSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forcing shape {0}.
        '''</summary>
        Public ReadOnly Property ECOSIM_DEFAULT_NEWFORCINGSHAPE() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWFORCINGSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediation shape {0}.
        '''</summary>
        Public ReadOnly Property ECOSIM_DEFAULT_NEWMEDIATIONSHAPE() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWMEDIATIONSHAPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New time series {0}.
        '''</summary>
        Public ReadOnly Property ECOSIM_DEFAULT_NEWTIMESERIES() As String
            Get
                Return ResourceManager.GetString("ECOSIM_DEFAULT_NEWTIMESERIES", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property Ecospace_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ecospace_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ecotracer_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ecotracer_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Editable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Expanded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expanded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ExportXMLHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportXMLHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Eye_closed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eye_closed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Eye_intermediate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eye_intermediate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Eye_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eye_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ESRI Asc files|*.asc.
        '''</summary>
        Public ReadOnly Property FILEFILTER_ASCFILE() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_ASCFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comma-separated text files (*.csv)|*.csv.
        '''</summary>
        Public ReadOnly Property FILEFILTER_CSV() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitmap image (*.bmp)|*.bmp|JPEG image (*.jpg;*.jpeg)|*.jpg;*.jpeg|GIF image (*.gif)|*.gif|PNG image (*.png)|*.png|TIFF image (*.tif;*.tiff)|*.tif;*.tiff.
        '''</summary>
        Public ReadOnly Property FILEFILTER_IMAGE() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_IMAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enhanced meta files|*.emf.
        '''</summary>
        Public ReadOnly Property FILEFILTER_IMAGE_EMF() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_IMAGE_EMF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitmap image|*.bmp|JPEG image|*.jpg;*.jpeg|GIF image|*.gif|PNG image|*.png|TIFF image|*.tif;*.tiff.
        '''</summary>
        Public ReadOnly Property FILEFILTER_IMAGE1() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_IMAGE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text files|*.txt.
        '''</summary>
        Public ReadOnly Property FILEFILTER_TEXT() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to : (colon).
        '''</summary>
        Public ReadOnly Property GENERIC_CHAR_COLON() As String
            Get
                Return ResourceManager.GetString("GENERIC_CHAR_COLON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to , (comma).
        '''</summary>
        Public ReadOnly Property GENERIC_CHAR_COMMA() As String
            Get
                Return ResourceManager.GetString("GENERIC_CHAR_COMMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to . (period).
        '''</summary>
        Public ReadOnly Property GENERIC_CHAR_PERIOD() As String
            Get
                Return ResourceManager.GetString("GENERIC_CHAR_PERIOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ; (semi-colon).
        '''</summary>
        Public ReadOnly Property GENERIC_CHAR_SEMICOLON() As String
            Get
                Return ResourceManager.GetString("GENERIC_CHAR_SEMICOLON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AED|UAE Dirham|AFN|Afghanistan Afghani|ALL|Albanian Lek|AMD|Armenian Dram|ANG|Antillean Guilder|AOR|Angolan New Kwanza|ARS|Argentinian Peso|AUD|Australian Dollar|AWG|Aruban Florin|AZM|Azerbaijan Manat|BAM|Bosnian Konvertibilna Marka|BBD|Barbadian Dollar|BDT|Bangladesh Taka|BGN|Bulgarian New Lev|BHD|Bahraini Dinar|BIF|Burundian Franc|BMD|Bermudan Dollar|BND|Brunei Dollar|BOB|Bolivian Boliviano|BRL|Brazilian Real|BSD|Bahamas Dollar|BTN|Bhutan Ngultrum|BWP|Botswana Pula|BYB|Belarussian Ruble|BZD|Belizean Dolla [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property GENERIC_CURRENCIES() As String
            Get
                Return ResourceManager.GetString("GENERIC_CURRENCIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; failed to save to file &apos;{1}&apos;: {2}..
        '''</summary>
        Public ReadOnly Property GENERIC_FILESAVE_FAILURE() As String
            Get
                Return ResourceManager.GetString("GENERIC_FILESAVE_FAILURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; is succesfully saved to file &apos;{1}&apos;..
        '''</summary>
        Public ReadOnly Property GENERIC_FILESAVE_SUCCES() As String
            Get
                Return ResourceManager.GetString("GENERIC_FILESAVE_SUCCES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Public ReadOnly Property GENERIC_LABEL_APPLY() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_APPLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {1}.
        '''</summary>
        Public ReadOnly Property GENERIC_LABEL_CURRENCY() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_CURRENCY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ({1}).
        '''</summary>
        Public ReadOnly Property GENERIC_LABEL_DETAIL() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_DETAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: ({1}, {2}).
        '''</summary>
        Public ReadOnly Property GENERIC_LABEL_GRAPHVALUE() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_GRAPHVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1}.
        '''</summary>
        Public ReadOnly Property GENERIC_LABEL_INDEXEDLABEL() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_INDEXEDLABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cursor.
        '''</summary>
        Public ReadOnly Property GENERIC_TEXT_CURSOR() As String
            Get
                Return ResourceManager.GetString("GENERIC_TEXT_CURSOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no data).
        '''</summary>
        Public ReadOnly Property GENERIC_TEXT_NODATA() As String
            Get
                Return ResourceManager.GetString("GENERIC_TEXT_NODATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (All).
        '''</summary>
        Public ReadOnly Property GENERIC_VALUE_ALL() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (N/A).
        '''</summary>
        Public ReadOnly Property GENERIC_VALUE_NOTAVAILABLE() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_NOTAVAILABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Public ReadOnly Property HEADER_ADD() As String
            Get
                Return ResourceManager.GetString("HEADER_ADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class.
        '''</summary>
        Public ReadOnly Property HEADER_CLASS() As String
            Get
                Return ResourceManager.GetString("HEADER_CLASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Public ReadOnly Property HEADER_CODE() As String
            Get
                Return ResourceManager.GetString("HEADER_CODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common name.
        '''</summary>
        Public ReadOnly Property HEADER_COMMON_NAME() As String
            Get
                Return ResourceManager.GetString("HEADER_COMMON_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Family.
        '''</summary>
        Public ReadOnly Property HEADER_FAMILY() As String
            Get
                Return ResourceManager.GetString("HEADER_FAMILY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Genus.
        '''</summary>
        Public ReadOnly Property HEADER_GENUS() As String
            Get
                Return ResourceManager.GetString("HEADER_GENUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index.
        '''</summary>
        Public ReadOnly Property HEADER_INDEX() As String
            Get
                Return ResourceManager.GetString("HEADER_INDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month.
        '''</summary>
        Public ReadOnly Property HEADER_MONTH() As String
            Get
                Return ResourceManager.GetString("HEADER_MONTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Public ReadOnly Property HEADER_NAME() As String
            Get
                Return ResourceManager.GetString("HEADER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order.
        '''</summary>
        Public ReadOnly Property HEADER_ORDER() As String
            Get
                Return ResourceManager.GetString("HEADER_ORDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phylum.
        '''</summary>
        Public ReadOnly Property HEADER_PHYLUM() As String
            Get
                Return ResourceManager.GetString("HEADER_PHYLUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relative weight.
        '''</summary>
        Public ReadOnly Property HEADER_RELATIVEWEIGHT() As String
            Get
                Return ResourceManager.GetString("HEADER_RELATIVEWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rel. weight.
        '''</summary>
        Public ReadOnly Property HEADER_RELATIVEWEIGHT_ABBR() As String
            Get
                Return ResourceManager.GetString("HEADER_RELATIVEWEIGHT_ABBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Species.
        '''</summary>
        Public ReadOnly Property HEADER_SPECIES() As String
            Get
                Return ResourceManager.GetString("HEADER_SPECIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Public ReadOnly Property HEADER_VALUE() As String
            Get
                Return ResourceManager.GetString("HEADER_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Values.
        '''</summary>
        Public ReadOnly Property HEADER_VALUES() As String
            Get
                Return ResourceManager.GetString("HEADER_VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Public ReadOnly Property HEADER_YEAR() As String
            Get
                Return ResourceManager.GetString("HEADER_YEAR", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property HomeHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HomeHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ImportXMLHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImportXMLHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property InsertPictureHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsertPictureHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Fleet:.
        '''</summary>
        Public ReadOnly Property LABEL_FLEET() As String
            Get
                Return ResourceManager.GetString("LABEL_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Group:.
        '''</summary>
        Public ReadOnly Property LABEL_GROUP() As String
            Get
                Return ResourceManager.GetString("LABEL_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Set:.
        '''</summary>
        Public ReadOnly Property LABEL_SET() As String
            Get
                Return ResourceManager.GetString("LABEL_SET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediating group (weighted) biomass.
        '''</summary>
        Public ReadOnly Property MEDIATION_X_AXIS_LABEL() As String
            Get
                Return ResourceManager.GetString("MEDIATION_X_AXIS_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xtract to CSV....
        '''</summary>
        Public ReadOnly Property MENU_EXTRACT_TO_CSV() As String
            Get
                Return ResourceManager.GetString("MENU_EXTRACT_TO_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Show legend.
        '''</summary>
        Public ReadOnly Property MENU_SHOW_LEGEND() As String
            Get
                Return ResourceManager.GetString("MENU_SHOW_LEGEND", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property NavBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property NavForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property NewDocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property NotEditable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotEditable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property OptionsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plugin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plugin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pluginpoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pluginpoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property PrintHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property PrintPreviewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintPreviewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete forcing or mediation function &apos;{0}&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Public ReadOnly Property PROMPT_SHAPE_DELETE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SHAPE_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete {0} forcing or mediation functions&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Public ReadOnly Property PROMPT_SHAPE_DELETE_MULTIPLE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SHAPE_DELETE_MULTIPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete time series &apos;{0}&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Public ReadOnly Property PROMPT_TIMESERIES_DELETE() As String
            Get
                Return ResourceManager.GetString("PROMPT_TIMESERIES_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete {0} time series&apos;. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Public ReadOnly Property PROMPT_TIMESERIES_DELETE_MULTIPLE() As String
            Get
                Return ResourceManager.GetString("PROMPT_TIMESERIES_DELETE_MULTIPLE", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property ProtectFormHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProtectFormHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change F.
        '''</summary>
        Public ReadOnly Property RUN_ECOSIM_F_VALUE_CAPTION() As String
            Get
                Return ResourceManager.GetString("RUN_ECOSIM_F_VALUE_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter F~value (or enter a string of comma separated F&apos;s for all fleets).
        '''</summary>
        Public ReadOnly Property RUN_ECOSIM_F_VALUE_MSG() As String
            Get
                Return ResourceManager.GetString("RUN_ECOSIM_F_VALUE_MSG", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property SaveAllHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAllHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property SaveModified() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveModified", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change shape type.
        '''</summary>
        Public ReadOnly Property SHAPE_TYPE_TO_SEASONAL_CAPTION() As String
            Get
                Return ResourceManager.GetString("SHAPE_TYPE_TO_SEASONAL_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing a shape from &apos;Long term&apos; to &apos;Seasonal&apos; will cause your long-term data to be overwritten by a seasonal pattern. This action cannot be undone. Are you sure you want to do this?.
        '''</summary>
        Public ReadOnly Property SHAPE_TYPE_TO_SEASONAL_MSG() As String
            Get
                Return ResourceManager.GetString("SHAPE_TYPE_TO_SEASONAL_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applying values, please wait.
        '''</summary>
        Public ReadOnly Property STATUS_APPLYVALUES() As String
            Get
                Return ResourceManager.GetString("STATUS_APPLYVALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adding time series {0} ....
        '''</summary>
        Public ReadOnly Property STATUS_TIMESERIES_ADDING() As String
            Get
                Return ResourceManager.GetString("STATUS_TIMESERIES_ADDING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating time series {0}....
        '''</summary>
        Public ReadOnly Property STATUS_TIMESERIES_UPDATING() As String
            Get
                Return ResourceManager.GetString("STATUS_TIMESERIES_UPDATING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set this value to all selected cells.
        '''</summary>
        Public ReadOnly Property TOOLTIP_GRID_APPLYVALUE() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_GRID_APPLYVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load grid content from a CSV file.
        '''</summary>
        Public ReadOnly Property TOOLTIP_GRID_LOADFROMCSV() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_GRID_LOADFROMCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save grid content to a CSV file.
        '''</summary>
        Public ReadOnly Property TOOLTIP_GRID_SAVETOCSV() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_GRID_SAVETOCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Average weight.
        '''</summary>
        Public ReadOnly Property TS_TYPE_AVERAGEWEIGHT() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_AVERAGEWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Absolute biomass.
        '''</summary>
        Public ReadOnly Property TS_TYPE_BIOMASSABS() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_BIOMASSABS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass forcing.
        '''</summary>
        Public ReadOnly Property TS_TYPE_BIOMASSFORCING() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_BIOMASSFORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relative biomass.
        '''</summary>
        Public ReadOnly Property TS_TYPE_BIOMASSREL() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_BIOMASSREL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catches.
        '''</summary>
        Public ReadOnly Property TS_TYPE_CATCHES() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_CATCHES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catches forcing.
        '''</summary>
        Public ReadOnly Property TS_TYPE_CATCHESFORCING() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_CATCHESFORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Constant total mortality.
        '''</summary>
        Public ReadOnly Property TS_TYPE_CONSTTOTALMORT() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_CONSTTOTALMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing effort.
        '''</summary>
        Public ReadOnly Property TS_TYPE_FISHINGEFFORT() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_FISHINGEFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing mortality.
        '''</summary>
        Public ReadOnly Property TS_TYPE_FISHINGMORT() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_FISHINGMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time forcing.
        '''</summary>
        Public ReadOnly Property TS_TYPE_TIMEFORCING() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_TIMEFORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total mortality.
        '''</summary>
        Public ReadOnly Property TS_TYPE_TOTALMORT() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_TOTALMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecotracer absolute concentration.
        '''</summary>
        Public ReadOnly Property TS_TYPE_TRACER_CONCABS() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_TRACER_CONCABS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecotracer relative concentration.
        '''</summary>
        Public ReadOnly Property TS_TYPE_TRACER_CONCREL() As String
            Get
                Return ResourceManager.GetString("TS_TYPE_TRACER_CONCREL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to kcal/m².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_CALORIE() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CALORIE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_CARBON() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_CARBON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to g/m².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_DRYWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_DRYWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to J/m².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_JOULES() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_JOULES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg N/m².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_NITROGEN() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_NITROGEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mg P/m².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_PHOSPOROUS() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_PHOSPOROUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t/km².
        '''</summary>
        Public ReadOnly Property UNIT_CURRENCY_WETWEIGHT() As String
            Get
                Return ResourceManager.GetString("UNIT_CURRENCY_WETWEIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day.
        '''</summary>
        Public ReadOnly Property UNIT_TIME_DAY() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_DAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to year.
        '''</summary>
        Public ReadOnly Property UNIT_TIME_YEAR() As String
            Get
                Return ResourceManager.GetString("UNIT_TIME_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DC|Diet||Diet composition.
        '''</summary>
        Public ReadOnly Property VARIABLE_DIETCOMP() As String
            Get
                Return ResourceManager.GetString("VARIABLE_DIETCOMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EE|||Ecotrophic Efficiency.
        '''</summary>
        Public ReadOnly Property VARIABLE_EEINPUT() As String
            Get
                Return ResourceManager.GetString("VARIABLE_EEINPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PB|P/B||Production over biomass.
        '''</summary>
        Public ReadOnly Property VARIABLE_PBINPUT() As String
            Get
                Return ResourceManager.GetString("VARIABLE_PBINPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QB|Q/B||Consumption over biomass.
        '''</summary>
        Public ReadOnly Property VARIABLE_QBINPUT() As String
            Get
                Return ResourceManager.GetString("VARIABLE_QBINPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catches.
        '''</summary>
        Public ReadOnly Property VARIABLE_TCATCHINPUT() As String
            Get
                Return ResourceManager.GetString("VARIABLE_TCATCHINPUT", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property WarningHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarningHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ZoomHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ZoomInHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomInHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ZoomOutHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomOutHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
