'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEMSEPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The distribution file {0} has non-living groups in it..
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRFILE_GROUPS_HASNONLIVING() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRFILE_GROUPS_HASNONLIVING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your distribution file for {0} contains the group &apos;{1}&apos; in it.{2}This is invalid because this group is a primary producer!.
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRFILE_GROUPS_INVALID_PRODUCER() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRFILE_GROUPS_INVALID_PRODUCER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The distribution file {0} does not have all the living groups in it..
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRFILE_GROUPS_LIVING_MISSING() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRFILE_GROUPS_LIVING_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The distribution file {0} has replicate groups in it..
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRFILE_GROUPS_REPLICATED() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRFILE_GROUPS_REPLICATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The distribution file for {0} has replicate groups in it..
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRPARAM_GROUPS_REPLICATED() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRPARAM_GROUPS_REPLICATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The distribution file for {0} does not have all the living groups that are not primary producers in it..
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRPARAM_GROUPS_TOOFEW() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRPARAM_GROUPS_TOOFEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The distribution file for {0} has too many groups in it..
        '''</summary>
        Friend ReadOnly Property ERROR_DISTRPARAM_GROUPS_TOOMANY() As String
            Get
                Return ResourceManager.GetString("ERROR_DISTRPARAM_GROUPS_TOOMANY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the directory to retrieve data from and output results to.
        '''</summary>
        Friend ReadOnly Property PROMPT_DATAPATH() As String
            Get
                Return ResourceManager.GetString("PROMPT_DATAPATH", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
