' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991- 
'    UBC Institute for the Oceans and Fisheries, Vancouver BC, Canada, and 
'    Ecopath International Initiative, Barcelona, Spain
' ===============================================================================
'

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwENetworkAnalysisRPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R program|R*.exe.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_R_EXE() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_R_EXE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R NETWRK script|*.r.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_R_SCRIPT() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_R_SCRIPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCOR files|*.dat.
        '''</summary>
        Friend ReadOnly Property FILFILTER_SCOR() As String
            Get
                Return ResourceManager.GetString("FILFILTER_SCOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select R program location.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_R_EXE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_R_EXE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select R script to execute.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_R_SCRIPT() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_R_SCRIPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select output SCOR file.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_SCOR_FILE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_SCOR_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rlogo_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rlogo_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCOR file could not be saved to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_SCOR_SAVED_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_SCOR_SAVED_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCOR file saved to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_SCOR_SAVED_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_SCOR_SAVED_SUCCESS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
