'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.296
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Eco_services
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://sirs.agrocampus-ouest.fr/EcoTroph/php/webser/operation_1.wsdl", ConfigurationName:="Eco_services.getResultPortType")>  _
    Public Interface getResultPortType
        
        'CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:sirs:getResult) du message list_modelsRequest ne correspond pas à la valeur par défaut (http://sirs.agrocampus-ouest.fr/EcoTroph/php/webser/operation_1.wsdl)
        <System.ServiceModel.OperationContractAttribute(Action:="list_models", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function list_models(ByVal request As Eco_services.list_modelsRequest) As Eco_services.list_modelsResponse
        
        'CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:sirs:getResult) du message getModelRequest ne correspond pas à la valeur par défaut (http://sirs.agrocampus-ouest.fr/EcoTroph/php/webser/operation_1.wsdl)
        <System.ServiceModel.OperationContractAttribute(Action:="getModel", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getModel(ByVal request As Eco_services.getModelRequest) As Eco_services.getModelResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="list_models", WrapperNamespace:="urn:sirs:getResult", IsWrapped:=true)>  _
    Partial Public Class list_modelsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public operation As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public model_number As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal operation As String, ByVal model_number As Integer)
            MyBase.New
            Me.operation = operation
            Me.model_number = model_number
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="list_modelsResponse", WrapperNamespace:="urn:sirs:getResult", IsWrapped:=true)>  _
    Partial Public Class list_modelsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public result As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As String)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getModel", WrapperNamespace:="urn:sirs:getResult", IsWrapped:=true)>  _
    Partial Public Class getModelRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public operation As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public model_number As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal operation As String, ByVal model_number As Integer)
            MyBase.New
            Me.operation = operation
            Me.model_number = model_number
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getModelResponse", WrapperNamespace:="urn:sirs:getResult", IsWrapped:=true)>  _
    Partial Public Class getModelResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public result As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As String)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface getResultPortTypeChannel
        Inherits Eco_services.getResultPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getResultPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Eco_services.getResultPortType)
        Implements Eco_services.getResultPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Eco_services_getResultPortType_list_models(ByVal request As Eco_services.list_modelsRequest) As Eco_services.list_modelsResponse Implements Eco_services.getResultPortType.list_models
            Return MyBase.Channel.list_models(request)
        End Function
        
        Public Function list_models(ByVal operation As String, ByVal model_number As Integer) As String
            Dim inValue As Eco_services.list_modelsRequest = New Eco_services.list_modelsRequest()
            inValue.operation = operation
            inValue.model_number = model_number
            Dim retVal As Eco_services.list_modelsResponse = CType(Me,Eco_services.getResultPortType).list_models(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Eco_services_getResultPortType_getModel(ByVal request As Eco_services.getModelRequest) As Eco_services.getModelResponse Implements Eco_services.getResultPortType.getModel
            Return MyBase.Channel.getModel(request)
        End Function
        
        Public Function getModel(ByVal operation As String, ByVal model_number As Integer) As String
            Dim inValue As Eco_services.getModelRequest = New Eco_services.getModelRequest()
            inValue.operation = operation
            inValue.model_number = model_number
            Dim retVal As Eco_services.getModelResponse = CType(Me,Eco_services.getResultPortType).getModel(inValue)
            Return retVal.result
        End Function
    End Class
End Namespace
