'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("My.Computer.FileSystem.SpecialDirectories.MyDocuments"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property LastSelectedDirectory() As String
        Get
            Return CType(Me("LastSelectedDirectory"),String)
        End Get
        Set
            Me("LastSelectedDirectory") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property MdbRecentlyUsedCount() As String
        Get
            Return CType(Me("MdbRecentlyUsedCount"),String)
        End Get
        Set
            Me("MdbRecentlyUsedCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property EiiRecentlyUsedCount() As String
        Get
            Return CType(Me("EiiRecentlyUsedCount"),String)
        End Get
        Set
            Me("EiiRecentlyUsedCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfAnyType xmlns:xsi=""http://www.w3"& _ 
        ".org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
        "anyType />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfAnyType>"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property MdbRecentlyUsedList() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("MdbRecentlyUsedList"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("MdbRecentlyUsedList") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfAnyType xmlns:xsi=""http://www.w3"& _ 
        ".org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
        "anyType />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfAnyType>"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property EiiRecentlyUsedList() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("EiiRecentlyUsedList"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("EiiRecentlyUsedList") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property FeedbackCriticalPopup() As Boolean
        Get
            Return CType(Me("FeedbackCriticalPopup"),Boolean)
        End Get
        Set
            Me("FeedbackCriticalPopup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property FeedbackCriticalStatusMessage() As Boolean
        Get
            Return CType(Me("FeedbackCriticalStatusMessage"),Boolean)
        End Get
        Set
            Me("FeedbackCriticalStatusMessage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property FeedbackWarningPopup() As Boolean
        Get
            Return CType(Me("FeedbackWarningPopup"),Boolean)
        End Get
        Set
            Me("FeedbackWarningPopup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property FeedbackWarningStatusMessage() As Boolean
        Get
            Return CType(Me("FeedbackWarningStatusMessage"),Boolean)
        End Get
        Set
            Me("FeedbackWarningStatusMessage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property FeedbackInformationPopup() As Boolean
        Get
            Return CType(Me("FeedbackInformationPopup"),Boolean)
        End Get
        Set
            Me("FeedbackInformationPopup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property FeedbackInformationStatusMessage() As Boolean
        Get
            Return CType(Me("FeedbackInformationStatusMessage"),Boolean)
        End Get
        Set
            Me("FeedbackInformationStatusMessage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property SaveContentLayout() As Boolean
        Get
            Return CType(Me("SaveContentLayout"),Boolean)
        End Get
        Set
            Me("SaveContentLayout") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute(""),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ContentLayoutSaveDirectory() As String
        Get
            Return CType(Me("ContentLayoutSaveDirectory"),String)
        End Get
        Set
            Me("ContentLayoutSaveDirectory") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property SettingLoaded() As Boolean
        Get
            Return CType(Me("SettingLoaded"),Boolean)
        End Get
        Set
            Me("SettingLoaded") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ForestGreen"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorESPressureText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorESPressureText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorESPressureText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0, 0, 244"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorComputedValuesText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorComputedValuesText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorComputedValuesText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Firebrick"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorErrorText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorErrorText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorErrorText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("DarkGoldenrod"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorFailedValidationText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorFailedValidationText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorFailedValidationText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Red"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorFailedResultText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorFailedResultText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorFailedResultText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorDefaultText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorDefaultText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorDefaultText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorNameText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorNameText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorNameText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LimeGreen"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorESProfitsText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorESProfitsText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorESProfitsText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MediumSeaGreen"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorESTotalCatchText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorESTotalCatchText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorESTotalCatchText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LavenderBlush"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorTrophicLinkText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorTrophicLinkText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorTrophicLinkText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorRemarksBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorRemarksBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorRemarksBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("255, 254, 225"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorSumBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorSumBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorSumBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("231, 235, 250"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorReadOnlyBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorReadOnlyBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorReadOnlyBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("176, 233, 173"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorCheckedBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorCheckedBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorCheckedBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MediumPurple"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorMissingParamBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorMissingParamBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorMissingParamBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorImageBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorImageBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorImageBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorPlotsBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorPlotsBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorPlotsBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ControlDark"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorMapBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorMapBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorMapBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorDefaultBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorDefaultBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorDefaultBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("232, 232, 232"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorNameBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorNameBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorNameBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property DisabledPlugins() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("DisabledPlugins"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("DisabledPlugins") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property FormPositions() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("FormPositions"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("FormPositions") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
    Public Property FeedbackMessageLogSize() As Integer
        Get
            Return CType(Me("FeedbackMessageLogSize"),Integer)
        End Get
        Set
            Me("FeedbackMessageLogSize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontTitle() As String
        Get
            Return CType(Me("FontTitle"),String)
        End Get
        Set
            Me("FontTitle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontLegend() As String
        Get
            Return CType(Me("FontLegend"),String)
        End Get
        Set
            Me("FontLegend") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontSubtitle() As String
        Get
            Return CType(Me("FontSubtitle"),String)
        End Get
        Set
            Me("FontSubtitle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontScale() As String
        Get
            Return CType(Me("FontScale"),String)
        End Get
        Set
            Me("FontScale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontValue() As String
        Get
            Return CType(Me("FontValue"),String)
        End Get
        Set
            Me("FontValue") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("48")>  _
    Public Property ThumbnailSize() As Integer
        Get
            Return CType(Me("ThumbnailSize"),Integer)
        End Get
        Set
            Me("ThumbnailSize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("UseDefault")>  _
    Public Property ShowLegends() As Global.Microsoft.VisualBasic.TriState
        Get
            Return CType(Me("ShowLegends"),Global.Microsoft.VisualBasic.TriState)
        End Get
        Set
            Me("ShowLegends") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScientificInterface.Settings
            Get
                Return Global.ScientificInterface.Settings.Default
            End Get
        End Property
    End Module
End Namespace
