' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991-2012 UBC Fisheries Centre, Vancouver BC, Canada.
' ===============================================================================
'
#Region " Imports "

Option Strict On
Imports EwEPlugin
Imports EwECore
Imports ScientificInterfaceShared.Controls
Imports EwEUtils.Core

#End Region ' Imports

''' ---------------------------------------------------------------------------
''' <summary>
''' The plug-in point.
''' </summary>
''' ---------------------------------------------------------------------------
Public Class cPluginPoint
    Implements EwEPlugin.IUIContextPlugin
    Implements EwEPlugin.IMenuItemPlugin
    Implements EwEPlugin.INavigationTreeItemPlugin

#Region " Private vars "

    Private m_frmUI As frmPlugin = Nothing
    Private m_uic As cUIContext = Nothing

#End Region ' Private vars

#Region " Plug-in points "

#Region " IPlugin "

    Public Sub Initialize(core As Object) _
        Implements EwEPlugin.IPlugin.Initialize
        ' Ignore
    End Sub

    Public ReadOnly Property Name As String _
        Implements EwEPlugin.IPlugin.Name
        Get
            Return "ndDFO_FF"
        End Get
    End Property

    Public ReadOnly Property Author As String _
        Implements EwEPlugin.IPlugin.Author
        Get
            Return "Fisheries and Oceans Canada"
        End Get
    End Property

    Public ReadOnly Property Contact As String _
        Implements EwEPlugin.IPlugin.Contact
        Get
            Return ""
        End Get
    End Property

    Public ReadOnly Property Description As String _
        Implements EwEPlugin.IPlugin.Description
        Get
            Return "Routine to read in multiple CSV files altering forcing functions for Ecosim simulations. This routine allows for single or multiple files to be read iteratively and applied to specific forcing functions using either monthly or annual values. Users have the ability to select which output files are generated by each Ecosim run."
        End Get
    End Property

#End Region ' IPlugin

#Region " UI Context "

    Public Sub UIContext(uic As Object) _
        Implements EwEPlugin.IUIContextPlugin.UIContext
        Me.m_uic = DirectCast(uic, cUIContext)
    End Sub

#End Region ' UI Context

#Region " GUI integration "

    Public ReadOnly Property ControlImage As System.Drawing.Image _
        Implements EwEPlugin.IGUIPlugin.ControlImage
        Get
            Return My.Resources.logo_canada
        End Get
    End Property

    Public Sub OnControlClick(sender As Object, e As System.EventArgs, ByRef frmPlugin As System.Windows.Forms.Form) _
        Implements EwEPlugin.IGUIPlugin.OnControlClick
        frmPlugin = Me.UI
    End Sub

    Public ReadOnly Property ControlText As String _
        Implements EwEPlugin.IGUIPlugin.ControlText
        Get
            Return "DFO FF Routine"
        End Get
    End Property

    Public ReadOnly Property ControlTooltipText As String _
        Implements EwEPlugin.IGUIPlugin.ControlTooltipText
        Get
            Return "DFO Forcing Function Routine"
        End Get
    End Property

    Public ReadOnly Property EnabledState As eCoreExecutionState _
        Implements EwEPlugin.IGUIPlugin.EnabledState
        Get
            Return EwEUtils.Core.eCoreExecutionState.EcosimLoaded
        End Get
    End Property

#End Region ' GUI integration

#Region " Menu item "

    Public ReadOnly Property MenuItemLocation As String _
        Implements EwEPlugin.IMenuItemPlugin.MenuItemLocation
        Get
            Return "MenuTools"
        End Get
    End Property

#End Region ' Menu item

#Region " Navigation tree "

    Public ReadOnly Property NavigationTreeItemLocation As String _
        Implements EwEPlugin.INavigationTreeItemPlugin.NavigationTreeItemLocation
        Get
            Return "ndTimeDynamic\ndEcosimTools"
        End Get
    End Property

#End Region ' Navigation tree

#End Region ' Plug-in point

#Region " Private helper methods "

    Private Function UI() As frmPlugin
        Dim bHasUI As Boolean = False

        If (Me.m_frmUI IsNot Nothing) Then
            bHasUI = Not Me.m_frmUI.IsDisposed
        End If

        If Not bHasUI Then
            Me.m_frmUI = New frmPlugin()
            Me.m_frmUI.UIContext = Me.m_uic
            Me.m_frmUI.Text = Me.ControlText
        End If

        Return Me.m_frmUI

    End Function

#End Region ' Private helper methods

End Class
