'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEResiliencePlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cicimar_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cicimar_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONACYT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONACYT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption matrices.
        '''</summary>
        Friend ReadOnly Property CONSWR_AUTOSAVE_ITEM() As String
            Get
                Return ResourceManager.GetString("CONSWR_AUTOSAVE_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption writer options....
        '''</summary>
        Friend ReadOnly Property CONSWR_MENU_ITEM() As String
            Get
                Return ResourceManager.GetString("CONSWR_MENU_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption matrices failed to save to {0}.
        '''</summary>
        Friend ReadOnly Property CONSWR_STATUS_SAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("CONSWR_STATUS_SAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption matrices saved to {0}.
        '''</summary>
        Friend ReadOnly Property CONSWR_STATUS_SAVE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("CONSWR_STATUS_SAVE_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder {0} cannot be created.
        '''</summary>
        Friend ReadOnly Property ERROR_NODIR() As String
            Get
                Return ResourceManager.GetString("ERROR_NODIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FixedAxesHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FixedAxesHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience.
        '''</summary>
        Friend ReadOnly Property GRAPH_RES_CAPTION() As String
            Get
                Return ResourceManager.GetString("GRAPH_RES_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience (annual).
        '''</summary>
        Friend ReadOnly Property GRAPH_RES_LINE_ANNUAL() As String
            Get
                Return ResourceManager.GetString("GRAPH_RES_LINE_ANNUAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reslience (monthly).
        '''</summary>
        Friend ReadOnly Property GRAPH_RES_LINE_MONTHLY() As String
            Get
                Return ResourceManager.GetString("GRAPH_RES_LINE_MONTHLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time.
        '''</summary>
        Friend ReadOnly Property GRAPH_RES_XAXIS_LABEL() As String
            Get
                Return ResourceManager.GetString("GRAPH_RES_XAXIS_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Computed resilience.
        '''</summary>
        Friend ReadOnly Property GRAPH_RES_YAXIS_LABEL() As String
            Get
                Return ResourceManager.GetString("GRAPH_RES_YAXIS_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supply-demand of energy ({0} {1}). Resilience: {2}.
        '''</summary>
        Friend ReadOnly Property GRAPH_SD_CAPTION() As String
            Get
                Return ResourceManager.GetString("GRAPH_SD_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Computed resilience.
        '''</summary>
        Friend ReadOnly Property GRAPH_SD_TREND() As String
            Get
                Return ResourceManager.GetString("GRAPH_SD_TREND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log (demand, consumption).
        '''</summary>
        Friend ReadOnly Property GRAPH_SD_XAXIS_LABEL() As String
            Get
                Return ResourceManager.GetString("GRAPH_SD_XAXIS_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log (supply, predation).
        '''</summary>
        Friend ReadOnly Property GRAPH_SD_YAXIS_LABEL() As String
            Get
                Return ResourceManager.GetString("GRAPH_SD_YAXIS_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IPN_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IPN_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience acknowledgements.
        '''</summary>
        Friend ReadOnly Property NAVTREE_ACKNOWLEDGEMENTS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_ACKNOWLEDGEMENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience plot.
        '''</summary>
        Friend ReadOnly Property NAVTREE_RESILIENCE() As String
            Get
                Return ResourceManager.GetString("NAVTREE_RESILIENCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience.
        '''</summary>
        Friend ReadOnly Property NAVTREE_ROOT() As String
            Get
                Return ResourceManager.GetString("NAVTREE_ROOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supply / demand plot.
        '''</summary>
        Friend ReadOnly Property NAVTREE_SUPPLY_DEMAND() As String
            Get
                Return ResourceManager.GetString("NAVTREE_SUPPLY_DEMAND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience plug-in data.
        '''</summary>
        Friend ReadOnly Property RESIL_AUTOSAVE_NAME() As String
            Get
                Return ResourceManager.GetString("RESIL_AUTOSAVE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecosim failed to run, cannot compute resilience.
        '''</summary>
        Friend ReadOnly Property RESIL_STATUS_RUNSIM() As String
            Get
                Return ResourceManager.GetString("RESIL_STATUS_RUNSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience data failed to save to {0}.
        '''</summary>
        Friend ReadOnly Property RESIL_STATUS_SAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("RESIL_STATUS_SAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resilience data saved to {0}.
        '''</summary>
        Friend ReadOnly Property RESIL_STATUS_SAVE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("RESIL_STATUS_SAVE_SUCCESS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
