'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEMPADynamicsPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (initial).
        '''</summary>
        Friend ReadOnly Property GENERIC_VALUE_INITIAL() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_INITIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA dynamics.
        '''</summary>
        Friend ReadOnly Property PLUGIN_TITLE() As String
            Get
                Return ResourceManager.GetString("PLUGIN_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select MPA closed state file to load.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_FILE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA Dynamics CSV file {0} faied to load. {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_LOAD_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_LOAD_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA Dynamics CSV file {0} loaded.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_LOAD_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_LOAD_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to closed to all fleets.
        '''</summary>
        Friend ReadOnly Property STATUS_FLEETS_CLOSED() As String
            Get
                Return ResourceManager.GetString("STATUS_FLEETS_CLOSED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to open to all fleets.
        '''</summary>
        Friend ReadOnly Property STATUS_FLEETS_OPEN() As String
            Get
                Return ResourceManager.GetString("STATUS_FLEETS_OPEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: updated {1}: {2}, {3}.
        '''</summary>
        Friend ReadOnly Property STATUS_MPA_CHANGED() As String
            Get
                Return ResourceManager.GetString("STATUS_MPA_CHANGED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to closed all year.
        '''</summary>
        Friend ReadOnly Property STATUS_YEAR_CLOSED() As String
            Get
                Return ResourceManager.GetString("STATUS_YEAR_CLOSED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to open all year.
        '''</summary>
        Friend ReadOnly Property STATUS_YEAR_OPEN() As String
            Get
                Return ResourceManager.GetString("STATUS_YEAR_OPEN", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
