'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwECustomPlugins.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Too many missing parameters. Parameter estimation aborted..
        '''</summary>
        Friend ReadOnly Property INFORMATION_MISSING_PARAMETERS() As String
            Get
                Return ResourceManager.GetString("INFORMATION_MISSING_PARAMETERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Too many loops. Parameter Estimation aborted..
        '''</summary>
        Friend ReadOnly Property INFORMATION_TOO_MANY_LOOPS() As String
            Get
                Return ResourceManager.GetString("INFORMATION_TOO_MANY_LOOPS", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MenuItem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuItem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecopath has estimated the biomass for group {0}, {1}, to be 0. This is because the fishery + migration + biomass accumulation is estimated to sum to 0. Please edit your data, allowing e.g. for biomass accumulation for this group..
        '''</summary>
        Friend ReadOnly Property PROMPT_ESTIMATE_BM_0() As String
            Get
                Return ResourceManager.GetString("PROMPT_ESTIMATE_BM_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diet for group {0} sums to {1}. Do you want to raise this to 1?.
        '''</summary>
        Friend ReadOnly Property PROMPT_NORMALIZE_DIET() As String
            Get
                Return ResourceManager.GetString("PROMPT_NORMALIZE_DIET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diet for one or more groups does not sum to 1. Select &apos;Yes&apos; to normalize diets to 1 for ALL predator groups..
        '''</summary>
        Friend ReadOnly Property PROMPT_NORMALIZE_DIET_ALL() As String
            Get
                Return ResourceManager.GetString("PROMPT_NORMALIZE_DIET_ALL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
