' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991- UBC Fisheries Centre, Vancouver BC, Canada.
' ===============================================================================
'

' ===============================================================================
' This class is manually generated via Visual Studio tool wsdl.exe

' Inspired by http://dotnetslackers.com/Community/blogs/kaushalparik/archive/2010/05/14/how-to-call-invoke-a-web-service-without-adding-web-reference.aspx
' Partially converted to VB.NET via http://www.developerfusion.com/tools/convert/csharp-to-vb/?batchId=907793bb-a406-4afc-9004-4e8071ad335d
' Converted VB file contained errors in the event firing logic, which were fixed by hand
' ===============================================================================
Option Strict On
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

''' <remarks>
''' This source code was auto-generated by wsdl, Version=4.0.30319.1.
''' </remarks>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")> _
<System.Diagnostics.DebuggerStepThroughAttribute()> _
<System.ComponentModel.DesignerCategoryAttribute("code")> _
<System.Web.Services.WebServiceBindingAttribute(Name:="getResultBinding", [Namespace]:="http://sirs.agrocampus-ouest.fr/EcoBase/php/webser/operation_1.wsdl")> _
Partial Public Class getResult
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private list_modelsOperationCompleted As System.Threading.SendOrPostCallback

    Private getModelOperationCompleted As System.Threading.SendOrPostCallback

    Public Sub New()
        Me.Url = "http://sirs.agrocampus-ouest.fr/EcoBase/php/webser/soap-server.php"
    End Sub

    Public Event list_modelsCompleted As list_modelsCompletedEventHandler

    Public Event getModelCompleted As getModelCompletedEventHandler

    <System.Web.Services.Protocols.SoapRpcMethodAttribute("list_models", RequestNamespace:="urn:sirs:getResult", ResponseNamespace:="urn:sirs:getResult")> _
    Public Function list_models(operation As String, model_number As Integer) As <System.Xml.Serialization.SoapElementAttribute("result")> String
        Dim results As Object() = Me.Invoke("list_models", New Object() {operation, model_number})
        Return DirectCast(results(0), String)
    End Function

    Public Function Beginlist_models(operation As String, model_number As Integer, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("list_models", New Object() {operation, model_number}, callback, asyncState)
    End Function

    Public Function Endlist_models(asyncResult As System.IAsyncResult) As String
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return DirectCast(results(0), String)
    End Function

    Public Sub list_modelsAsync(operation As String, model_number As Integer)
        Me.list_modelsAsync(operation, model_number, Nothing)
    End Sub

    Public Sub list_modelsAsync(operation As String, model_number As Integer, userState As Object)
        If (Me.list_modelsOperationCompleted Is Nothing) Then
            Me.list_modelsOperationCompleted = New System.Threading.SendOrPostCallback(AddressOf Me.Onlist_modelsOperationCompleted)
        End If
        Me.InvokeAsync("list_models", New Object() {operation, model_number}, Me.list_modelsOperationCompleted, userState)
    End Sub

    Private Sub Onlist_modelsOperationCompleted(arg As Object)
        Try
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = DirectCast(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent list_modelsCompleted(Me, New list_modelsCompletedEventArgs(invokeArgs.Results, invokeArgs.[Error], invokeArgs.Cancelled, invokeArgs.UserState))
        Catch ex As Exception
            ' Whoah
        End Try
    End Sub

    <System.Web.Services.Protocols.SoapRpcMethodAttribute("getModel", RequestNamespace:="urn:sirs:getResult", ResponseNamespace:="urn:sirs:getResult")> _
    Public Function getModel(operation As String, model_number As Integer) As <System.Xml.Serialization.SoapElementAttribute("result")> String
        Dim results As Object() = Me.Invoke("getModel", New Object() {operation, model_number})
        Return DirectCast(results(0), String)
    End Function

    Public Function BegingetModel(operation As String, model_number As Integer, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getModel", New Object() {operation, model_number}, callback, asyncState)
    End Function

    Public Function EndgetModel(asyncResult As System.IAsyncResult) As String
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return DirectCast(results(0), String)
    End Function

    Public Sub getModelAsync(operation As String, model_number As Integer)
        Me.getModelAsync(operation, model_number, Nothing)
    End Sub

    Public Sub getModelAsync(operation As String, model_number As Integer, userState As Object)
        If (Me.getModelOperationCompleted Is Nothing) Then
            Me.getModelOperationCompleted = New System.Threading.SendOrPostCallback(AddressOf Me.OngetModelOperationCompleted)
        End If
        Me.InvokeAsync("getModel", New Object() {operation, model_number}, Me.getModelOperationCompleted, userState)
    End Sub

    Private Sub OngetModelOperationCompleted(arg As Object)
        Try
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = DirectCast(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent getModelCompleted(Me, New getModelCompletedEventArgs(invokeArgs.Results, invokeArgs.[Error], invokeArgs.Cancelled, invokeArgs.UserState))
        Catch ex As Exception

        End Try
    End Sub

    Public Shadows Sub CancelAsync(userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")> _
Public Delegate Sub list_modelsCompletedEventHandler(sender As Object, e As list_modelsCompletedEventArgs)

''' <remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")> _
<System.Diagnostics.DebuggerStepThroughAttribute()> _
<System.ComponentModel.DesignerCategoryAttribute("code")> _
Partial Public Class list_modelsCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results As Object()

    Friend Sub New(results As Object(), exception As System.Exception, cancelled As Boolean, userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub

    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary()
            Return DirectCast(Me.results(0), String)
        End Get
    End Property
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")> _
Public Delegate Sub getModelCompletedEventHandler(sender As Object, e As getModelCompletedEventArgs)

<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")> _
<System.Diagnostics.DebuggerStepThroughAttribute()> _
<System.ComponentModel.DesignerCategoryAttribute("code")> _
Partial Public Class getModelCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results As Object()

    Friend Sub New(results As Object(), exception As System.Exception, cancelled As Boolean, userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub

    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary()
            Return DirectCast(Me.results(0), String)
        End Get
    End Property

End Class