'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FishMIPv3Plugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BioDiversityPlugin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BioDiversityPlugin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FishMIP configuration.
        '''</summary>
        Friend ReadOnly Property CAPTION() As String
            Get
                Return ResourceManager.GetString("CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load EwE run protocol.
        '''</summary>
        Friend ReadOnly Property CAPTION_LOADPROTOCOL() As String
            Get
                Return ResourceManager.GetString("CAPTION_LOADPROTOCOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to read file {0}.
        '''</summary>
        Friend ReadOnly Property CSV_READ_ERROR() As String
            Get
                Return ResourceManager.GetString("CSV_READ_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ecoocean_768px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ecoocean_768px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EwE run protocol file|*.protocol.
        '''</summary>
        Friend ReadOnly Property FILEFILTER() As String
            Get
                Return ResourceManager.GetString("FILEFILTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FishMIP_logo_plain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FishMIP_logo_plain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EwE configuration updated.
        '''</summary>
        Friend ReadOnly Property MESSAGE_CONFIG() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Layer {0} connected to driver {1}: {2}.
        '''</summary>
        Friend ReadOnly Property MESSAGE_DETAIL_DRIVER() As String
            Get
                Return ResourceManager.GetString("MESSAGE_DETAIL_DRIVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time series {0} loaded: {1}.
        '''</summary>
        Friend ReadOnly Property MESSAGE_DETAIL_TIMESERIES_SET() As String
            Get
                Return ResourceManager.GetString("MESSAGE_DETAIL_TIMESERIES_SET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time series unloaded.
        '''</summary>
        Friend ReadOnly Property MESSAGE_DETAIL_TMESERIES_CLEAR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_DETAIL_TMESERIES_CLEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External dataset not defined.
        '''</summary>
        Friend ReadOnly Property MESSAGE_ERROR_DRIVER_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ERROR_DRIVER_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time series not loaded.
        '''</summary>
        Friend ReadOnly Property MESSAGE_ERROR_TIMESERIES_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ERROR_TIMESERIES_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property triatlas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triatlas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property triatlas_fish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triatlas_fish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are conflcts applying time series.
        '''</summary>
        Friend ReadOnly Property TS_CONFLICT() As String
            Get
                Return ResourceManager.GetString("TS_CONFLICT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Period {0} uses social scenario {1} with time series {2}.
        '''</summary>
        Friend ReadOnly Property TS_CONFLICT_DETAIL() As String
            Get
                Return ResourceManager.GetString("TS_CONFLICT_DETAIL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
