name: Build Check
on:
  push:
    branches:
      - Upgrade_To_SDK_Style

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Ensure github-Official-EwE NuGet source
        run: |
          if (dotnet nuget list source | Select-String "github-Official-EwE") {
            dotnet nuget remove source github-Official-EwE
          }
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
            --name "github-Official-EwE `
            --username ${{ github.repository_owner }} `
            --password ${{ secrets.GITHUB_TOKEN }} `
            --store-password-in-clear-text
        shell: pwsh

      - name: Use custom NuGet build check action
        uses: Official-EwE/Eii.GithubActions/BuildCheckNet48Net80@master    # can also be BuildCheckNet48Net80@v.. etcc
        with:
          solution-file: ./Sources/EwE6.sln
