name: Build Check
on:
  pull_request:
    branches:
      - cEwEEFDatabase   # EXPERIMENTAL branch added

jobs:
  build:
    runs-on: windows-2025-vs2026
    permissions:
      contents: read
      packages: read

    steps:
      - name: Use custom NuGet build check action
        uses: Official-EwE/Eii.GithubActions/BuildCheckWindows@master
        with:
          solution-file: ./Sources/EwE6.sln
